CREATE USER IF NOT EXISTS cd IDENTIFIED BY 'p';
GRANT USAGE ON *.* TO cd;

CREATE DATABASE IF NOT EXISTS cd CHARACTER SET utf8;

GRANT ALL PRIVILEGES ON cd.* to cd;

CREATE TABLESPACE `cdspace` ADD DATAFILE 'cdspace.ibd' ENGINE=INNODB;
