@startuml Use Cases

actor Gast
actor Admin
actor Kunde

rectangle cd {
    Gast --> (Cd suchen)
    Admin --> (Cd suchen)
    Admin --> (Cd anlegen)
    Admin --> (Cd ändern)
    Admin --> (Cd löschen)
    Kunde --> (Cd suchen)
    Kunde --> (Cd anlegen)
    Kunde --> (Cd ändern)
}

footer (c) Finn Lamberti

@enduml
